### ISSUE TITLE
test failures building the project annotationPipeline

### ISSUE THREAD

**Issue by ldelgado-serrano** [cBioPortal/genome-nexus-annotation-pipeline#243]
Hi, 
I'm trying to build the project annotationPipeline but got an error:

Test set: org.cbioportal.annotation.SpringBatchIntegrationTest
-------------------------------------------------------------------------------
Tests run: 18, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 22.057 s <<< FAILURE! - in org.cbioportal.annotation.SpringBatchIntegrationTest
check_if_maf_file_still_the_same_when_annotating_with_mskcc_transcripts  Time elapsed: 0.546 s  <<< FAILURE!
org.junit.ComparisonFailure: Line number 15 does not match. expected:<...       202     244                     ENST00000[407796.2:c.49G>A      p.Glu17Lys      p.E17K  ENST00000407796 NM_001014431.1  17      Gag/Aag 3/14]   SUCCESS> but was:<...   202     244                     ENST00000[349310.3:c.49G>A      p.Glu17Lys      p.E17K  ENST00000349310 NM_001014432.1  17      Gag/Aag 4/15]   SUCCESS>
        at org.cbioportal.annotation.SpringBatchIntegrationTest.testWith(SpringBatchIntegrationTest.java:405)
        at org.cbioportal.annotation.SpringBatchIntegrationTest.check_if_maf_file_still_the_same_when_annotating_with_mskcc_transcripts(SpringBatchIntegrationTest.java:92)

I'll appreciate any help. 
Thanks, 

Luisa.

**Comment by NoeRzPz** [comment]
Hi, 
I got the same problem:
```
[ERROR] Tests run: 18, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 19.668 s <<< FAILURE! - in org.cbioportal.annotation.SpringBatchIntegrationTest
[ERROR] org.cbioportal.annotation.SpringBatchIntegrationTest.run_vcf2maf_test_case_mskcc  Time elapsed: 1.164 s  <<< ERROR!
java.lang.IllegalStateException: Line number 20 does not match.
	at org.springframework.util.Assert.state(Assert.java:76)
	at org.springframework.batch.test.AssertFile.assertFileEquals(AssertFile.java:46)
	at org.springframework.batch.test.AssertFile.assertFileEquals(AssertFile.java:61)
	at org.cbioportal.annotation.SpringBatchIntegrationTest.testWith(SpringBatchIntegrationTest.java:387)
	at org.cbioportal.annotation.SpringBatchIntegrationTest.run_vcf2maf_test_case_mskcc(SpringBatchIntegrationTest.java:191)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestExecutionCallbacks.evaluate(RunBeforeTestExecutionCallbacks.java:76)
```
Did you managed to solve it? 
My application.properties file is:
```spring.main.web-application-type=none
spring.batch.job.enabled=false
genomenexus.base=https://grch38.genomenexus.org
genomenexus.isoform_query_parameter=isoformOverrideSource
genomenexus.enrichment_fields=annotation_summary,my_variant_info,polyphen,sift,Mutation Assessor,nucleotide_context
chunk=10
oncokb.token=
```
And my log4j.properties:
```
# Change INFO to DEBUG, if you want to see debugging info on underlying libraries we use.
log4j.rootLogger=INFO, stdout

# Change INFO to DEBUG, if you want see debugging info on our packages only.
log4j.category.org.mskcc=INFO
#log4j.category.org.springframework=ALL

#log4j.logger.org.springframework.security=DEBUG
#log4j.logger.org.springframework.integration=DEBUG


# Use the JVM option, e.g.: "java -DPORTAL_HOME=/pathto/portal_homedir",
# or - "java -DPORTAL_HOME=$PORTAL_HOME", where PORTAL_HOME is shell (environment) variable.

## IMPORTANT - THRESHOLD SHOULD NOT BE DEBUG FOR PRODUCTION, CREDENTIALS CAN BE DISPLAYED!

log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.Target=System.out
log4j.appender.stdout.layout = org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern = %d{yyyy-MM-dd HH:mm:ss} [%t] %-5p %c - %m%n

#log4j.logger.org.hibernate=INFO, a
#log4j.logger.org.hibernate.SQL=DEBUG
#log4j.logger.org.hibernate.type=TRACE
#log4j.logger.org.hibernate.hql.ast.AST=info
#log4j.logger.org.hibernate.tool.hbm2ddl=warn
#log4j.logger.org.hibernate.hql=debug
#log4j.logger.org.hibernate.cache=info
#log4j.logger.org.hibernate.jdbc=debug
```
